openapi: 3.0.0
info:
  title: URL Shortner API
  version: 1.0.0
  description: |-
    An API to create and get shortened URL from long URL
paths:
  /ping:
    get:
      summary: Ping
      operationId: getPing
      description: Ping Endpoint
      responses:
        200:
          $ref: "#/components/responses/Ping"
  /url/{shortUrl}:
    get:
      summary: Get Long URL
      operationId: getURL
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: The short URL code
          schema:
            type: string
      responses:
        301:
          description: Redirect to the original long URL
          headers:
            Location:
              description: The URL to redirect to
              schema:
                type: string
        400:
          $ref: "#/components/responses/Error"
        500:
          $ref: "#/components/responses/Error"
    delete:
      summary: Delete Long URL
      operationId: deleteURL
      parameters:
        - name: shortUrl
          in: path
          required: true
          description: The short URL code
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/DeleteUrl"
        400:
          $ref: "#/components/responses/Error"
        500:
          $ref: "#/components/responses/Error"
  
  /url:
    post:
      summary: Create short url
      operationId: postURL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/request"
      responses:
        201:
          $ref: "#/components/responses/CreateUrl"
        400:
          $ref: "#/components/responses/Error"
        500:
          $ref: "#/components/responses/Error"
components:
  schemas:
    request:
      type: object
      properties:
        url:
          type: string
          description: "URL to shorten"
          example: "https://github.com/ankitsalunkhe"
      required:
        - url
  responses:
    Ping:
      description: Ping response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "https://git.com/asdf123"
    DeleteUrl:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "https://git.com/asdf123"
            required:
              - message
    CreateUrl:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              url:
                type: string
                example: "https://git.com/asdf123"
            required:
              - url
    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'unable to create shortened url'
            required:
              - message